//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace gallery.Models
{
    #region Контексты
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    public partial class pictersDB : ObjectContext
    {
        #region Конструкторы
    
        /// <summary>
        /// Инициализирует новый объект pictersDB, используя строку соединения из раздела "pictersDB" файла конфигурации приложения.
        /// </summary>
        public pictersDB() : base("name=pictersDB", "pictersDB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта pictersDB.
        /// </summary>
        public pictersDB(string connectionString) : base(connectionString, "pictersDB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта pictersDB.
        /// </summary>
        public pictersDB(EntityConnection connection) : base(connection, "pictersDB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Разделяемые методы
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Свойства ObjectSet
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<pictures> pictures
        {
            get
            {
                if ((_pictures == null))
                {
                    _pictures = base.CreateObjectSet<pictures>("pictures");
                }
                return _pictures;
            }
        }
        private ObjectSet<pictures> _pictures;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<ques> ques
        {
            get
            {
                if ((_ques == null))
                {
                    _ques = base.CreateObjectSet<ques>("ques");
                }
                return _ques;
            }
        }
        private ObjectSet<ques> _ques;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Users> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<Users>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<Users> _Users;

        #endregion
        #region Методы AddTo
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet pictures. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddTopictures(pictures pictures)
        {
            base.AddObject("pictures", pictures);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet ques. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToques(ques ques)
        {
            base.AddObject("ques", ques);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Users. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }

        #endregion
    }
    

    #endregion
    
    #region Сущности
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pictersDBModel1", Name="pictures")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class pictures : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта pictures.
        /// </summary>
        /// <param name="id">Исходное значение свойства id.</param>
        /// <param name="nazva">Исходное значение свойства nazva.</param>
        /// <param name="avtor">Исходное значение свойства avtor.</param>
        /// <param name="img">Исходное значение свойства img.</param>
        /// <param name="price">Исходное значение свойства price.</param>
        public static pictures Createpictures(global::System.Int32 id, global::System.String nazva, global::System.String avtor, global::System.String img, global::System.Decimal price)
        {
            pictures pictures = new pictures();
            pictures.id = id;
            pictures.nazva = nazva;
            pictures.avtor = avtor;
            pictures.img = img;
            pictures.price = price;
            return pictures;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nazva
        {
            get
            {
                return _nazva;
            }
            set
            {
                OnnazvaChanging(value);
                ReportPropertyChanging("nazva");
                _nazva = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nazva");
                OnnazvaChanged();
            }
        }
        private global::System.String _nazva;
        partial void OnnazvaChanging(global::System.String value);
        partial void OnnazvaChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String avtor
        {
            get
            {
                return _avtor;
            }
            set
            {
                OnavtorChanging(value);
                ReportPropertyChanging("avtor");
                _avtor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("avtor");
                OnavtorChanged();
            }
        }
        private global::System.String _avtor;
        partial void OnavtorChanging(global::System.String value);
        partial void OnavtorChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String img
        {
            get
            {
                return _img;
            }
            set
            {
                OnimgChanging(value);
                ReportPropertyChanging("img");
                _img = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("img");
                OnimgChanged();
            }
        }
        private global::System.String _img;
        partial void OnimgChanging(global::System.String value);
        partial void OnimgChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.Decimal _price;
        partial void OnpriceChanging(global::System.Decimal value);
        partial void OnpriceChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pictersDBModel1", Name="ques")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ques : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта ques.
        /// </summary>
        /// <param name="id">Исходное значение свойства id.</param>
        public static ques Createques(global::System.Int32 id)
        {
            ques ques = new ques();
            ques.id = id;
            return ques;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String question
        {
            get
            {
                return _question;
            }
            set
            {
                OnquestionChanging(value);
                ReportPropertyChanging("question");
                _question = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("question");
                OnquestionChanged();
            }
        }
        private global::System.String _question;
        partial void OnquestionChanging(global::System.String value);
        partial void OnquestionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pictersDBModel1", Name="Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Users : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Users.
        /// </summary>
        /// <param name="id">Исходное значение свойства id.</param>
        public static Users CreateUsers(global::System.Int32 id)
        {
            Users users = new Users();
            users.id = id;
            return users;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adress
        {
            get
            {
                return _adress;
            }
            set
            {
                OnadressChanging(value);
                ReportPropertyChanging("adress");
                _adress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("adress");
                OnadressChanged();
            }
        }
        private global::System.String _adress;
        partial void OnadressChanging(global::System.String value);
        partial void OnadressChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tel
        {
            get
            {
                return _tel;
            }
            set
            {
                OntelChanging(value);
                ReportPropertyChanging("tel");
                _tel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tel");
                OntelChanged();
            }
        }
        private global::System.String _tel;
        partial void OntelChanging(global::System.String value);
        partial void OntelChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String id_pic
        {
            get
            {
                return _id_pic;
            }
            set
            {
                Onid_picChanging(value);
                ReportPropertyChanging("id_pic");
                _id_pic = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("id_pic");
                Onid_picChanged();
            }
        }
        private global::System.String _id_pic;
        partial void Onid_picChanging(global::System.String value);
        partial void Onid_picChanged();

        #endregion
    
    }

    #endregion
    
}
